export const services = [
  {
    id: "agentic-ai-finance",
    number: "01",
    title: "Agentic AI for the Office of Finance",
    shortTitle: "Office of Finance",
    tagline: "Flagship Practice · Office of Finance",
    slug: "/services/agentic-ai-finance",
    seo: {
      title: "Agentic AI for Finance Teams — AP, AR & Month-End Close Automation | AgenticSense",
      description: "AgenticSense deploys AI agents that own AP, AR, GL and month-end close end to end — natively inside SAP Business One and Oracle Fusion Cloud, with full audit trails and zero manual steps.",
    },
    hero: {
      headline: "Your Finance Team Shouldn't Be Keying the Same Invoice Twice.",
      highlight: "Keying the Same Invoice Twice.",
      sub: "We deploy AI agents that own Accounts Payable, Accounts Receivable, General Ledger and month-end close — end to end, natively inside your ERP. The agent finishes the job. No manual steps in the middle. No exceptions batch that sits for days.",
      cta1: "Book a Free Finance Assessment",
      cta2: "See How Agents Work",
      trustLabel: "Built for enterprise on",
      badges: ["SAP Business One", "Oracle Fusion Cloud", "Microsoft Fabric"],
    },
    overview: {
      heading: "Autonomous Finance — Built at the Level of the Posting Logic",
      lead: "Finance automation fails when it stops at extraction. Our agents go all the way — they capture, validate, match, post and reconcile inside your ERP — so your team reviews exceptions, not data.",
      body: "This is our flagship practice. We understand AP, AR, GL and the month-end close at the level of the posting logic, matching rules and intercompany controls — not the slide. Every agent ships with full audit logging, configurable approval gates and human-in-the-loop review on the exceptions that genuinely need judgement.",
      stats: [
        { val: "100%", label: "Actions audit-logged" },
        { val: "3-Way", label: "PO/GRN match standard" },
        { val: "0", label: "Manual ERP steps mid-workflow" },
        { val: "Weeks", label: "Pilot to production" },
      ],
      cards: [
        { title: "AP — Accounts Payable", body: "Invoice capture, 2- and 3-way PO/GRN matching, exception handling and straight-through posting to your ERP." },
        { title: "AR — Accounts Receivable", body: "Invoice generation, collections follow-up, cash application and dispute triage — all agent-driven." },
        { title: "GL & Reconciliations", body: "Journal preparation, intercompany matching and balance-sheet reconciliation with variance flagging." },
        { title: "Month-End Close", body: "Task orchestration, accruals, variance analysis and close-status reporting — the close your team has been waiting for." },
      ],
    },
    benefits: [
      { icon: "⚡", title: "Processing time cut — not trimmed", body: "Invoices that moved in days move in minutes. Not because someone works faster, but because the agent never stops between steps." },
      { icon: "🔒", title: "Every action is auditable", body: "Every decision, match, post and exception flag is logged. You have a complete audit trail that survives the next compliance review." },
      { icon: "🎯", title: "Human attention goes where it matters", body: "Your team reviews the exceptions that genuinely need judgement. The rest — the 80–90% that follows the rules — the agent handles without interruption." },
      { icon: "📊", title: "Month-end closes faster", body: "Close-orchestration agents prepare journals, reconcile and surface variances while the period is still open — not after it's too late." },
      { icon: "🛡", title: "No brittle middleware", body: "Built natively on SAP Service Layer and Oracle Fusion REST APIs. Your automation survives the next ERP upgrade without a rebuild." },
      { icon: "🌐", title: "Multi-entity ready", body: "One deployment can span multiple business units, currencies and entity structures — with consolidated reporting built in." },
    ],
    features: [
      { num: "01", title: "Multi-channel invoice intake", body: "Email webhook, web upload and API ingestion — the agent captures from wherever invoices arrive." },
      { num: "02", title: "Vision-AI data extraction", body: "High-accuracy extraction from PDFs, scanned documents and structured forms — no templates required." },
      { num: "03", title: "2-way and 3-way matching", body: "Automated PO and GRN matching with configurable tolerances and vendor-specific rules." },
      { num: "04", title: "Straight-through ERP posting", body: "Clean transactions post directly to SAP Business One or Oracle Fusion — no intermediary staging." },
      { num: "05", title: "Exception queues with context", body: "Exceptions surface with the matching evidence, not just a flag — so reviewers decide faster." },
      { num: "06", title: "Collections and cash application", body: "AR agents follow up on outstanding invoices, apply cash receipts and triage disputes without a human touchpoint." },
      { num: "07", title: "Journal and accruals automation", body: "GL agents draft recurring journals, calculate accruals and flag variance against budget or prior period." },
      { num: "08", title: "Close-status dashboard", body: "Real-time visibility of close progress, open items and outstanding reconciliations — for finance leadership." },
    ],
    process: [
      { num: "01", title: "Discover", body: "We map your AP/AR/GL workflows, volumes and pain points, and separate what is deployable immediately from what needs to be built." },
      { num: "02", title: "Design", body: "Target architecture, matching rules, approval gates, exception handling logic and success metrics — agreed in writing before build." },
      { num: "03", title: "Build", body: "Agent development against your real ERP data and integration constraints. We prove it works in your environment, not a sandbox." },
      { num: "04", title: "Deploy", body: "Production go-live with monitoring, audit logging, human-in-the-loop checkpoints and safeguards active from day one." },
      { num: "05", title: "Scale", body: "Expand coverage across AP, AR, GL, close and into adjacent processes — with continuous tuning and performance reporting." },
    ],
    whyUs: {
      heading: "Finance-First, ERP-Native — and Accountable for Results",
      points: [
        { title: "We understand the posting logic, not just the language", body: "We have built production agents that post invoices, apply cash and prepare journals inside SAP and Oracle. That depth is not available from a general AI consultancy." },
        { title: "No manual steps — by design, not by aspiration", body: "Full end-to-end automation is a contractual standard on every finance engagement. The agent finishes the workflow." },
        { title: "Official APIs — no fragile middleware", body: "We build on SAP Service Layer and Oracle Fusion REST APIs. Your automation survives upgrades because it uses the same interfaces SAP and Oracle maintain." },
        { title: "One team from roadmap to production", body: "No handoffs between strategy and build teams. The people who design your agent build it, deploy it and support it post-launch." },
      ],
      box: {
        heading: "Built for Your Compliance Environment",
        body: "Enterprise finance has non-negotiable requirements: segregation of duties, audit trails, access controls and regulatory reporting. We build these in from day one — not retrofitted before the audit.",
        stats: [
          { val: "100%", label: "Agent actions logged and traceable" },
          { val: "0", label: "Third-party connectors in our builds" },
          { val: "HITL", label: "Human-in-loop on every exception" },
        ],
      },
    },
    faqs: [
      { q: "Do your AP agents need our team to manually approve every invoice?", a: "No. Invoices that meet your matching rules and tolerance thresholds post straight through without any human action. Only genuine exceptions — mismatches, missing POs, tolerance overruns — are routed for review, with the evidence attached so decisions take seconds, not minutes." },
      { q: "Which ERPs do you integrate with for finance automation?", a: "Our primary finance platforms are SAP Business One (via Service Layer REST API and SAP HANA), Oracle Fusion Cloud (via REST APIs and OCI GenAI Agents) and Microsoft Fabric. We also support NetSuite, Odoo and Zoho Books for AP/AR workflows." },
      { q: "How do you handle multi-entity or multi-currency environments?", a: "We build for your entity structure from the start — including intercompany transactions, currency revaluation and consolidated reporting requirements. Multi-entity setups are a standard delivery pattern, not a custom add-on." },
      { q: "What happens if the agent encounters a document it can't process?", a: "The agent routes it to your exception queue with context — what it extracted, what it couldn't verify, and which rule it failed against. Your team makes the call with full information. The agent never discards a document silently." },
      { q: "Can we start with just AP before expanding to AR and close?", a: "Yes. Most engagements start with one high-volume, well-defined workflow — typically AP — prove value in production, then expand. You are never committed to a full rollout before seeing results." },
    ],
    cta: {
      heading: "Tell Us the Workflow That Costs Your Finance Team the Most Time.",
      body: "In a free Finance Automation Assessment, we will map your single highest-value opportunity, sketch how an agent handles it inside your ERP, and give you an honest view of effort, impact and what is deployable today — at no cost and no obligation.",
      cta1: "Book Your Free Assessment",
      cta2: "Request a Demo",
    },
    relatedServices: ["erp-crm-ai-integration", "intelligent-document-processing", "ai-governance-security-mlops"],
  },
  {
    id: "erp-crm-ai-integration",
    number: "02",
    title: "Enterprise ERP & CRM-Native AI Integration",
    shortTitle: "ERP & CRM Integration",
    tagline: "ERP & CRM Integration · Official APIs Only",
    slug: "/services/erp-crm-ai-integration",
    seo: {
      title: "SAP Business One AI, Oracle Fusion & NetSuite AI Integration | AgenticSense",
      description: "AgenticSense connects AI agents directly to SAP B1, Oracle Fusion Cloud, NetSuite, Odoo, Zoho and Salesforce via official APIs — upgrade-safe, zero middleware, fully automated.",
    },
    hero: {
      headline: "AI That Plugs Into Your Enterprise Systems — Natively.",
      highlight: "Your Enterprise Systems — Natively.",
      sub: "Every ERP integration we build uses the vendor's own supported interfaces. No third-party connectors. No middleware that breaks at the next upgrade. Just clean, production-grade AI that runs where your data lives.",
      cta1: "Discuss Your Integration",
      cta2: "See the Platforms We Support",
      trustLabel: "Native integration across",
      badges: ["SAP Business One", "Oracle Fusion", "NetSuite", "Salesforce"],
    },
    overview: {
      heading: "The Connector Is the Weak Link. We Remove It.",
      lead: "Most AI integrations rely on third-party middleware that breaks whenever the ERP updates. We take a different position: if an official API exists, we use it.",
      body: "We connect intelligent agents directly to your enterprise platforms — from SAP Business One's Service Layer and HANA to Oracle Fusion's REST APIs and OCI GenAI infrastructure — so your automation is robust, upgrade-safe and completely owned by you.",
      stats: [
        { val: "8+", label: "Enterprise platforms natively integrated" },
        { val: "Zero", label: "Third-party connectors used" },
        { val: "Linux", label: "Production deployment environment" },
        { val: "Custom", label: "Built from scratch — no templates" },
      ],
      cards: [
        { title: "SAP Business One", body: "Service Layer REST API and SAP HANA direct connection — the official production path, not a screen-scraping workaround." },
        { title: "Oracle Fusion Cloud", body: "REST APIs, OCI GenAI Agents and AI Agent Studio — full AI-native integration with Oracle's own intelligence layer." },
        { title: "NetSuite, Odoo & Zoho", body: "SuiteTalk REST/SuiteScript, official JSON-RPC and REST APIs — clean integrations for mid-market ERP environments." },
        { title: "Salesforce & Microsoft", body: "Salesforce REST/Bulk APIs plus Microsoft Fabric, Azure AI Foundry and Entra ID for secure, governed cloud integration." },
      ],
    },
    benefits: [
      { icon: "", title: "Survives every ERP upgrade", body: "Official APIs are maintained by the vendor. When SAP or Oracle releases an update, your integration keeps working — because it was built the right way." },
      { icon: "", title: "Your data never leaves your control", body: "Deployed on your own Linux production environment. No third-party service sitting between your agent and your ERP data." },
      { icon: "", title: "Enterprise identity and access", body: "Secure authentication via Microsoft Entra ID / Azure AD and OCI IAM — your access controls respected at every layer." },
      { icon: "", title: "Custom-built, not configured", body: "No pre-built connectors with hidden limitations. Every integration is engineered for your specific data model, permissions structure and workflows." },
      { icon: "", title: "Multi-platform, single delivery team", body: "One team manages your entire integration landscape — SAP, Oracle, Salesforce and beyond — with a consistent architecture and support model." },
      { icon: "", title: "Scales with your platform mix", body: "As your enterprise stack evolves — new ERPs, additional CRMs, cloud migrations — your AI integration layer extends without a rebuild." },
    ],
    features: [
      { num: "SAP", title: "SAP Business One — Service Layer & HANA", body: "REST API integration via Service Layer for transactional operations, direct HANA SQL for reporting and complex GRN-to-LC mapping." },
      { num: "ORA", title: "Oracle Fusion Cloud — REST & OCI GenAI", body: "Full REST API coverage plus OCI GenAI Agents and AI Agent Studio for intelligent, governance-aware Oracle automation." },
      { num: "NS", title: "NetSuite — SuiteTalk REST & SuiteScript", body: "Official SuiteTalk REST and SuiteScript/RESTlet integrations — no SOAP, no unofficial endpoints, no future-proofing risk." },
      { num: "OD", title: "Odoo — JSON-RPC & REST API", body: "Odoo's official REST and JSON-RPC APIs, supporting operations across Accounting, Purchase, Inventory and CRM modules." },
      { num: "ZH", title: "Zoho Books & CRM — Official REST", body: "Complete coverage across Zoho Books for finance workflows and Zoho CRM for sales and service automation." },
      { num: "SF", title: "Salesforce — REST & Bulk APIs", body: "CRM-driven agent workflows using Salesforce REST and Bulk APIs — for sales operations, service automation and revenue intelligence." },
      { num: "MS", title: "Microsoft Fabric & Azure AI Foundry", body: "Data lakehouse pipelines on Fabric with model services from Azure AI Foundry — the modern Microsoft enterprise data stack, fully integrated." },
      { num: "ID", title: "Microsoft Entra ID / Azure AD & OCI IAM", body: "Secure identity and access management across all integrations — your existing SSO and RBAC model respected throughout." },
    ],
    process: [
      { num: "01", title: "Platform Audit", body: "We review your ERP version, API access, licensing and data model before any architecture decisions." },
      { num: "02", title: "API Path Design", body: "We map every required operation to its official API endpoint — and identify where custom paths are needed." },
      { num: "03", title: "Agent Integration Build", body: "Development against your real environment, with identity, error handling and retry logic built in." },
      { num: "04", title: "Regression & Upgrade Test", body: "We test against your ERP version and its next planned release before go-live." },
      { num: "05", title: "Managed Operations", body: "Ongoing monitoring, upgrade compatibility checks and performance tuning post-launch." },
    ],
    whyUs: {
      heading: "ERP-Native by Design, Enterprise-Grade in Practice",
      points: [
        { title: "Official APIs only — no workarounds", body: "We use the same interfaces SAP, Oracle and Salesforce maintain for their own certified partners. Your integration is upgrade-safe because it was built correctly." },
        { title: "No third-party middleware in the chain", body: "Every system in your integration landscape connects directly — no iPaaS, no connector platforms, no hidden dependencies that introduce failure points." },
        { title: "Custom-built for your data model", body: "Your entity structure, custom fields and approval hierarchies are built into the integration — not forced into a generic template." },
        { title: "One team across your entire stack", body: "SAP, Oracle, Salesforce and Microsoft — managed by a single team with a consistent architecture. No separate vendor for each platform." },
      ],
      box: {
        heading: "Upgrade-Safe by Design",
        body: "Every integration we build is tested against your current ERP version and its next planned release — so an upgrade announcement is not a crisis.",
        stats: [
          { val: "8+", label: "Enterprise platforms supported" },
          { val: "Zero", label: "Third-party connectors used" },
          { val: "API", label: "Official interfaces only — always" },
        ],
      },
    },
    faqs: [
      { q: "What if our ERP doesn't have an API for the operation we need?", a: "We engineer a clean, supported alternative — whether that's a direct HANA SQL connection for SAP, a SuiteScript RESTlet for NetSuite, or an approved extension pattern for Oracle. We never use screen scraping or unofficial methods that break on updates." },
      { q: "Will this affect our ERP support agreement or licensing?", a: "No. We use official, vendor-sanctioned APIs — the same interfaces used by SAP's own certified add-ons and Oracle's own cloud services. Your support agreement and licensing are unaffected." },
      { q: "Can you integrate with multiple ERPs in a single engagement?", a: "Yes. Large enterprises often run SAP alongside Oracle or NetSuite for different entities. We have built cross-platform integrations and can manage a mixed-ERP landscape within a single agent deployment." },
      { q: "How do you handle security credentials and secrets management?", a: "All credentials are managed with AES-256 encryption, stored securely and never hard-coded. Access is controlled through your existing Entra ID or OCI IAM — no new identity system to manage." },
    ],
    cta: {
      heading: "Ready to Connect Your ERP to Production-Grade AI?",
      body: "Tell us which platforms are in your landscape and what you want them to do. We'll give you a clear view of the integration path, the effort involved and what is deployable against your current setup — at no cost.",
      cta1: "Start the Conversation",
      cta2: "See a Platform Demo",
    },
    relatedServices: ["agentic-ai-finance", "custom-ai-agent-development", "ai-governance-security-mlops"],
  },
  {
    id: "intelligent-document-processing",
    number: "03",
    title: "Intelligent Document Processing & Invoice Automation",
    shortTitle: "Document Processing",
    tagline: "Document Intelligence · Invoice Automation",
    slug: "/services/intelligent-document-processing",
    seo: {
      title: "Intelligent Document Processing & Invoice Automation for Enterprise ERP | AgenticSense",
      description: "AgenticSense turns unstructured invoices, contracts and vendor documents into posted, reconciled ERP transactions — automatically. High-accuracy AI extraction, 3-way matching, straight-through posting.",
    },
    hero: {
      headline: "Every Vendor Invoice. Extracted, Matched, Posted — Automatically.",
      highlight: "Extracted, Matched, Posted — Automatically.",
      sub: "Invoices arrive as PDFs and emails. Our document agents extract the data, validate it against your ERP records, match to PO and goods receipt, and post straight through — with exceptions routed, not discarded.",
      cta1: "Book a Document Automation Demo",
      cta2: "See the Matching Logic",
      trustLabel: "Proven in production on",
      badges: ["SAP Business One", "Oracle Fusion", "NetSuite"],
    },
    overview: {
      heading: "From Unstructured Document to Posted Transaction — No Human in Between",
      lead: "Vendor invoices, receipts, contracts and forms arrive in every format imaginable. Our document agents handle them all — extracting with vision-capable AI, validating against your ERP records, matching to supporting documents and posting the result directly into your system of record.",
      body: "Transactions that meet your rules go straight through. Exceptions — mismatches, tolerance overruns, missing POs — are routed to your exception queue with the evidence attached, so reviewers make fast, informed decisions.",
      stats: [
        { val: "High", label: "Extraction accuracy — vision AI" },
        { val: "3-Way", label: "PO/GRN/Invoice matching" },
        { val: "STP", label: "Straight-through posting — zero touch" },
        { val: "Full", label: "Audit trail on every document" },
      ],
      cards: [
        { title: "Multi-Channel Intake", body: "Email webhook, web upload and API ingestion — invoices captured wherever they arrive, automatically." },
        { title: "Vision-AI Extraction", body: "High-accuracy extraction from PDFs, scans and structured forms — handles vendor formats without templates." },
        { title: "Configurable Matching", body: "PO and GRN matching tolerances set per vendor, per document type — with audit trail for every decision." },
        { title: "Exception Management", body: "Clear exception queues with matching evidence. Human reviewers decide fast — the agent never discards silently." },
      ],
    },
    benefits: [
      { icon: "", title: "Hours reduced to seconds", body: "Document processing that took a finance analyst minutes per invoice now completes in seconds — for every invoice in the queue, simultaneously." },
      { icon: "", title: "Errors caught before they post", body: "The matching logic catches discrepancies before anything hits the ERP. Vendor-supplied errors, duplicate invoices and tolerance overruns are flagged — not passed through." },
      { icon: "", title: "Full document provenance", body: "Every extracted field, every match decision and every exception route is logged. You have complete traceability from document receipt to posted transaction." },
      { icon: "", title: "Handles every format and channel", body: "PDFs, scanned images, emailed invoices, uploaded documents — the agent processes them all through the same extraction and validation pipeline." },
      { icon: "", title: "Scales without adding headcount", body: "Process ten times the invoice volume with the same team. The agent's throughput scales with your business — your people stay focused on exceptions." },
      { icon: "", title: "Integrates with your existing process", body: "Exception queues, approval workflows and ERP posting can be configured to match your existing controls — no process redesign required to go live." },
    ],
    features: [
      { num: "01", title: "Email webhook intake", body: "Invoices forwarded or received at a dedicated inbox are picked up automatically — no manual upload required." },
      { num: "02", title: "Web upload portal", body: "Suppliers and internal teams can upload documents directly through a branded portal, triggering immediate processing." },
      { num: "03", title: "Vision-AI field extraction", body: "Vendor name, invoice number, line items, totals, tax, dates and payment terms — extracted with vision-capable models, not brittle OCR templates." },
      { num: "04", title: "ERP record cross-validation", body: "Extracted data validated against your live ERP — vendor master, open POs, approved amounts and goods receipt records." },
      { num: "05", title: "2-way and 3-way match", body: "Configurable tolerance thresholds per vendor and document class. Match logic documented and auditable." },
      { num: "06", title: "Straight-through ERP posting", body: "Matched invoices post directly to SAP Business One, Oracle Fusion or NetSuite — zero human touchpoint on clean transactions." },
      { num: "07", title: "Duplicate detection", body: "Cross-reference against previously processed invoices — same vendor, same amount, same date patterns flagged before they reach the ERP." },
      { num: "08", title: "Exception queue with evidence", body: "Every exception surfaces with extracted values, the matched record and the specific rule that failed — reviewers decide in one click." },
    ],
    process: [
      { num: "01", title: "Ingest", body: "Document arrives via email, upload or API. The agent timestamps receipt and assigns a tracking reference." },
      { num: "02", title: "Extract", body: "Vision AI reads every field. Confidence scores flag low-certainty extractions for review before they proceed." },
      { num: "03", title: "Validate", body: "Extracted data is cross-checked against your ERP vendor master, open POs and GRN records in real time." },
      { num: "04", title: "Match or Route", body: "Clean matches post straight through. Exceptions are queued with context — never discarded, never silently failed." },
      { num: "05", title: "Audit & Report", body: "Every step logged. Processing reports, throughput dashboards and exception analytics available in real time." },
    ],
    whyUs: {
      heading: "Vision-AI Extraction Built for Vendor Reality",
      points: [
        { title: "No templates required", body: "Vision-AI extraction adapts to each vendor's invoice format without template setup. Onboarding a new vendor costs nothing." },
        { title: "Production-standard matching logic", body: "Our 3-way matching logic is built from real AP workflows — tolerances, exception types and posting rules match how your finance team actually works." },
        { title: "Audit trail from document to transaction", body: "Complete provenance: receipt timestamp, extracted values, match decision, exception route, posting confirmation — every step logged." },
        { title: "Handles the difficult documents", body: "Scanned invoices, poor-quality PDFs, non-standard layouts — vision-capable models handle what traditional OCR cannot." },
      ],
      box: {
        heading: "Straight-Through Processing",
        body: "The goal is maximum straight-through rate — invoices that meet your rules post without human intervention. Exceptions get context, not confusion.",
        stats: [
          { val: "STP", label: "Straight-through posting standard" },
          { val: "3-Way", label: "PO/GRN/Invoice match built in" },
          { val: "Full", label: "Audit trail on every document" },
        ],
      },
    },
    faqs: [
      { q: "What document formats can the extraction agent handle?", a: "PDFs (both text-layer and scanned/image-based), email body invoices, structured form uploads and most common image formats. Vision-capable models handle scanned documents that traditional OCR cannot read reliably." },
      { q: "Do we need to set up a template for each of our vendors?", a: "No. Vision-AI extraction adapts to each vendor's invoice format without templates. Vendor-specific rules (such as tolerance thresholds or required fields) are configurable without format mapping." },
      { q: "What happens to an invoice that can't be matched?", a: "It moves to your exception queue — with the extracted values, the GRN or PO it was matched against, and a plain-language explanation of why it didn't pass. Nothing is discarded without a human decision." },
      { q: "Can the agent handle landed cost and multi-line invoices?", a: "Yes. We have production experience with landed cost workflows and multi-line vendor invoices across manufacturing and distribution clients — including complex customs broker scenarios." },
    ],
    cta: {
      heading: "Show Us Your Highest-Volume Document Workflow.",
      body: "In a free session, we'll map your document pipeline, identify where automation creates the most value and show you exactly what a production-grade document agent looks like against your real documents — at no cost.",
      cta1: "Book a Free Assessment",
      cta2: "Request a Demo",
    },
    relatedServices: ["agentic-ai-finance", "erp-crm-ai-integration", "custom-ai-agent-development"],
  },
  {
    id: "custom-ai-agent-development",
    number: "04",
    title: "Custom AI Agent Development",
    shortTitle: "Custom AI Agents",
    tagline: "Custom Build · Multi-Agent Systems",
    slug: "/services/custom-ai-agent-development",
    seo: {
      title: "Custom AI Agent Development — Multi-Agent Systems for Enterprise | AgenticSense",
      description: "AgenticSense engineers bespoke multi-agent AI systems using LangGraph, FastAPI and enterprise-grade LLMs — built for your workflows, your tools and your governance requirements.",
    },
    hero: {
      headline: "When Off-the-Shelf Won't Fit, We Engineer It From First Principles.",
      highlight: "We Engineer It From First Principles.",
      sub: "We design and ship custom, tool-using agents and multi-agent systems that plan, act and verify — orchestrated for reliability, wrapped in the controls an enterprise requires, built on the model that fits your environment.",
      cta1: "Discuss Your Agent Requirements",
      cta2: "See Our Build Stack",
      trustLabel: "Built on",
      badges: ["LangGraph", "FastAPI", "Claude / GPT / Gemini", "OCI & Azure"],
    },
    overview: {
      heading: "Agents Built for Your Workflows — Not Built Around Someone Else's",
      lead: "Every enterprise has workflows that don't fit the template. The approval chain that spans four systems. The reconciliation that needs to reason across two data sources. The onboarding process that branches across seven conditions. We build the agents that handle these.",
      body: "Our custom agent development practice covers the full engineering spectrum — from single task agents to multi-agent orchestration systems with planning, tool use, retrieval, verification and human-in-the-loop controls. Model-flexible. Enterprise-hardened. Shipped to production.",
      stats: [
        { val: "Multi", label: "Agent orchestration with LangGraph" },
        { val: "4+", label: "LLM families supported" },
        { val: "HITL", label: "Human review on every critical path" },
        { val: "RAG", label: "Retrieval over your own data" },
      ],
      cards: [
        { title: "Multi-Agent Orchestration", body: "LangGraph-based orchestration with defined agent roles, tool routing, state management and failure handling." },
        { title: "Tool & System Integration", body: "Agents that use your real tools — ERP APIs, databases, search, email, calendars, external services." },
        { title: "Retrieval-Augmented Reasoning", body: "RAG pipelines over your own documents, policies and data — grounded responses, not hallucinated ones." },
        { title: "Model-Flexible Architecture", body: "Built to run on Anthropic Claude, OpenAI GPT, Google Gemini, OCI or Azure models — your choice, your cost profile." },
      ],
    },
    benefits: [
      { icon: "🔧", title: "Fits your exact workflow", body: "No compromises on edge cases, approval structures or data formats. The agent is designed for your process, not the other way around." },
      { icon: "🏰", title: "Enterprise controls from day one", body: "Guardrails, approval gates, human-in-the-loop checkpoints and retry logic are not add-ons — they are part of the initial design." },
      { icon: "🧠", title: "Reasons over your own data", body: "RAG pipelines give agents access to your policies, historical records and domain knowledge — no general-knowledge hallucination risk." },
      { icon: "🔀", title: "Multi-agent coordination", body: "Complex workflows split across specialised agents — each owns its domain, passes context cleanly and verifies before acting." },
      { icon: "💰", title: "Model cost is your call", body: "We build model-flexible architectures. As models improve and costs drop, your agent runs on a more capable and cheaper model without re-engineering." },
      { icon: "📦", title: "Fully owned by you", body: "The code is yours. Deployed on your infrastructure. No vendor dependency, no per-seat licensing and no black-box behaviour." },
    ],
    features: [
      { num: "01", title: "LangGraph multi-agent orchestration", body: "Directed graph-based agent workflows with explicit state, conditional routing and cycle handling — production-grade, not experimental." },
      { num: "02", title: "FastAPI backend architecture", body: "Async FastAPI services for agent execution, tool integration and external API calls — high-performance, maintainable, containerised." },
      { num: "03", title: "Vector search and RAG pipelines", body: "pgvector or dedicated vector stores for document retrieval — giving agents access to your proprietary knowledge base." },
      { num: "04", title: "Tool use and function calling", body: "Agents that call real APIs, run database queries, read files, send emails and update records — not just generate text." },
      { num: "05", title: "Human-in-the-loop checkpoints", body: "Configurable approval gates, retry logic and verification steps — so critical actions always go through the right human before execution." },
      { num: "06", title: "LLM model flexibility", body: "Anthropic Claude, OpenAI GPT-4o, Google Gemini, OCI GenAI and Azure OpenAI — selected for your accuracy, cost and data-residency requirements." },
      { num: "07", title: "Gunicorn multi-worker deployment", body: "Production-grade WSGI serving with Gunicorn, Redis for state/caching and Celery for background task orchestration." },
      { num: "08", title: "Full observability", body: "Logging of every agent action, tool call, model response and decision point — with monitoring dashboards and alerting from day one." },
    ],
    process: [
      { num: "01", title: "Requirements", body: "We map the workflow, identify every tool and system the agent needs to use, and define the boundaries between autonomous action and human review." },
      { num: "02", title: "Architecture", body: "Agent graph design, tool schema definition, RAG pipeline architecture and model selection — documented before a line of code." },
      { num: "03", title: "Build & Integrate", body: "Agent development in iterative sprints, tested against your real data sources and real integrations from the first sprint." },
      { num: "04", title: "Harden & Evaluate", body: "Adversarial testing, edge-case handling, guardrail validation and performance benchmarking before go-live." },
      { num: "05", title: "Deploy & Operate", body: "Production deployment with monitoring, alerting and ongoing optimisation. You own the code; we provide the expertise." },
    ],
    whyUs: {
      heading: "Engineering Depth That Generic AI Firms Can't Match",
      points: [
        { title: "We build from first principles", body: "No pre-built templates, no off-the-shelf connectors. Every agent is engineered for your specific workflow, data model and integration landscape." },
        { title: "Model-agnostic by architecture", body: "Your agent is not locked to one LLM provider. We build the architecture so you can switch models as the landscape evolves — without rebuilding." },
        { title: "Production is the only standard", body: "We do not build demos. Every agent we ship is tested against real data, real integrations and real edge cases before it touches production." },
        { title: "The code is yours", body: "Full code ownership, clean documentation and structured handover. No vendor lock-in, no black boxes, no ongoing licensing dependency." },
      ],
      box: {
        heading: "Model-Flexible. Enterprise-Hardened.",
        body: "Built to run on the model that fits your requirements today — and to switch as the landscape improves, without a rebuild.",
        stats: [
          { val: "4+", label: "LLM families supported natively" },
          { val: "100%", label: "Code ownership — no lock-in" },
          { val: "HITL", label: "Human controls on every critical path" },
        ],
      },
    },
    faqs: [
      { q: "How is a custom agent different from using an AI platform or SaaS product?", a: "A SaaS AI product is built for the average use case. A custom agent is engineered for yours — your data model, your approval logic, your integration landscape and your governance requirements. The edge cases that break generic products are handled because we designed for them." },
      { q: "Which LLM should we use?", a: "We recommend the model that fits your accuracy requirements, data-residency constraints and cost profile — not the model we have a commercial arrangement with. We have production experience with Anthropic Claude, OpenAI GPT-4o, Google Gemini and Oracle OCI GenAI." },
      { q: "Do we need a data team or AI team on our side?", a: "No. We handle architecture, build, integration, deployment and operations. Your team defines the business requirements and reviews outputs. We provide the engineering depth — you stay focused on the outcome." },
      { q: "Can an agent you build be extended later by our internal team?", a: "Yes. We write clean, documented code with a clear architecture. We also provide a structured handover and can train your team to extend and maintain the agent. There are no lock-in mechanisms." },
    ],
    cta: {
      heading: "Describe the Workflow That Doesn't Fit Any Off-the-Shelf Product.",
      body: "We've heard it before. Tell us what you need — the process, the systems involved and the outcome you're after. We'll tell you how we would engineer it, what the build looks like and what you should expect from a first pilot.",
      cta1: "Start the Technical Conversation",
      cta2: "See Example Agent Architectures",
    },
    relatedServices: ["erp-crm-ai-integration", "conversational-ai-enterprise-copilots", "ai-governance-security-mlops"],
  },
  {
    id: "conversational-ai-enterprise-copilots",
    number: "05",
    title: "Conversational AI & Enterprise Copilots",
    shortTitle: "Conversational AI",
    tagline: "Conversational AI · Enterprise Copilots",
    slug: "/services/conversational-ai-enterprise-copilots",
    seo: {
      title: "Enterprise AI Copilots & Conversational AI for ERP Data | AgenticSense",
      description: "AgenticSense builds enterprise copilots that let your finance, operations and support teams query ERP data in plain language — grounded in real records, permission-aware, deployable in Teams, Outlook and your own apps.",
    },
    hero: {
      headline: "Ask Your Systems a Question. Get an Answer Backed by Your Data.",
      highlight: "Get an Answer Backed by Your Data.",
      sub: "Your ERP holds the answers. Your team shouldn't need an IT ticket to reach them. We build copilots that let finance, operations and support ask in plain language — and get responses grounded in real, permission-controlled records.",
      cta1: "See a Copilot Demo",
      cta2: "Explore Deployment Options",
      trustLabel: "Deployable via",
      badges: ["Microsoft Teams", "Outlook", "Web Widget", "Your Own Apps"],
    },
    overview: {
      heading: "Natural Language Access to Your Enterprise Intelligence",
      lead: "Leadership shouldn't wait on analysts to pull data from Oracle Fusion before understanding where the numbers stand. Internal teams shouldn't need IT support to query their own systems.",
      body: "Our copilots sit on top of your enterprise data and deliver accurate, permission-aware answers in seconds. Every response is grounded in your live ERP records — not general knowledge, not cached reports from last Tuesday. Access controls are respected at every turn.",
      stats: [
        { val: "Real", label: "Live ERP data — not cached reports" },
        { val: "RBAC", label: "Permission-aware at every query" },
        { val: "NL", label: "Plain-language query — no SQL" },
        { val: "Multi", label: "Channel delivery across Teams, web, apps" },
      ],
      cards: [
        { title: "Finance Copilot", body: "Query AR balances, AP status, GL accounts and close progress in plain English — instant, grounded responses for finance leadership." },
        { title: "Operations Copilot", body: "Inventory levels, order status, supplier performance and fulfilment metrics — available to operations teams without an IT request." },
        { title: "Customer & Vendor Assistant", body: "External-facing assistants for order status, invoice queries and self-service — reducing your support queue without reducing service quality." },
        { title: "Analytics Self-Service", body: "Natural-language reporting and drill-down analytics — from executive dashboards to operational line items, on demand." },
      ],
    },
    benefits: [
      { icon: "⚡", title: "Answers in seconds, not hours", body: "Reporting requests that required an analyst to pull, format and send data are answered instantly — from your live system." },
      { icon: "🔐", title: "Governance is built in", body: "Users see only what their role permits. No risk of finance data reaching unauthorised staff — the copilot respects your RBAC at query time." },
      { icon: "📉", title: "Support queue shrinks", body: "Customer and vendor assistants handle order status, invoice enquiries and routine support — your human team focuses on exceptions." },
      { icon: "🧩", title: "Deploys where your team works", body: "Microsoft Teams, Outlook, web widget or embedded in your own applications — no new tool for your team to adopt." },
      { icon: "📊", title: "Grounded in your data — always", body: "Responses come from live records, not general AI knowledge. Accuracy is a function of your data quality, not the model's training set." },
      { icon: "🔗", title: "Works across your systems", body: "A finance copilot can draw from SAP, Oracle and Salesforce simultaneously — joining data your team currently has to stitch manually." },
    ],
    features: [
      { num: "01", title: "Natural-language ERP querying", body: "'Show me all invoices over $50k that haven't been approved' — answered from your live ERP in plain language." },
      { num: "02", title: "Variance analysis on demand", body: "Actual vs budget, period over period and trend analysis — surfaced in a conversational response, not a static report." },
      { num: "03", title: "Self-service analytics drill-down", body: "Users can ask follow-up questions to drill from a summary figure to the underlying transactions — without IT involvement." },
      { num: "04", title: "Customer and vendor self-service", body: "External-facing assistants answer order status, invoice and payment queries using your live ERP data." },
      { num: "05", title: "Permission-aware responses", body: "Every response is filtered through your role-based access controls — the copilot cannot return data the user is not authorised to see." },
      { num: "06", title: "Multi-system data joining", body: "A single question can draw from SAP, Oracle Fusion and Salesforce — the copilot joins the answer, not the user." },
      { num: "07", title: "Teams and Outlook integration", body: "Deployed as a Teams bot or Outlook add-in — available inside the tools your team already uses, with zero additional login." },
      { num: "08", title: "Shadow DOM web widget", body: "An isolated, brand-able web widget deployable on any page — your vendor portal, intranet or public-facing site." },
    ],
    process: [
      { num: "01", title: "Data Discovery", body: "We map your enterprise data sources, access control structure and most common reporting and query patterns." },
      { num: "02", title: "RAG & Query Design", body: "We build the retrieval pipeline, define query boundaries and configure the permission layer before the copilot interface exists." },
      { num: "03", title: "Copilot Build", body: "Conversational interface, grounding logic, guardrails and fallback responses — built and tested against real queries from your team." },
      { num: "04", title: "Channel Deployment", body: "Teams bot, Outlook add-in, web widget or embedded API — deployed through your channel with your branding and governance." },
      { num: "05", title: "Monitor & Improve", body: "Query logging, accuracy tracking and continuous improvement based on how your team actually uses the copilot in production." },
    ],
    whyUs: {
      heading: "Copilots That Know What They Don't Know",
      points: [
        { title: "Grounded in live data, not training data", body: "Every response comes from your ERP at query time. The copilot cannot fabricate a figure — it can only return what is in your system." },
        { title: "Permission model is not optional", body: "Access controls are baked into the query layer. A finance director and a warehouse manager get different answers to the same question — correctly." },
        { title: "Deploys where your team already works", body: "Microsoft Teams, Outlook, web widget or your own app — no new tool adoption required. The copilot comes to your team, not the other way around." },
        { title: "Multi-system without multi-vendor complexity", body: "One copilot can draw from SAP, Oracle and Salesforce simultaneously. One team builds it, one team supports it." },
      ],
      box: {
        heading: "Real-Time ERP Intelligence",
        body: "Answers grounded in live records, not yesterday's cached report. Permission-aware at every query — always.",
        stats: [
          { val: "Live", label: "Real-time ERP data at every query" },
          { val: "RBAC", label: "Permission-aware responses always" },
          { val: "4+", label: "Deployment channels supported" },
        ],
      },
    },
    faqs: [
      { q: "Can the copilot make changes to our ERP, or is it read-only?", a: "By default, copilots are read-only — they query and surface data. We can add write actions (creating a record, triggering a workflow) with appropriate approval gates, but this is configured explicitly and requires human confirmation for any system change." },
      { q: "How does the copilot stay accurate as our ERP data changes?", a: "Copilots query your live ERP at query time — they are not working from a cached snapshot. Responses reflect the state of your data when the question is asked." },
      { q: "What stops a user from asking a question outside their permission level?", a: "The copilot applies your role-based access controls at the data layer — before the response is composed. If a user's role does not have access to a dataset, the copilot cannot include it in a response, regardless of how the question is phrased." },
      { q: "Can we have a customer-facing version for vendor or client portals?", a: "Yes. We build external-facing assistants that answer order status, payment and invoice queries using scoped, authenticated access to your ERP — with a separate permission layer from your internal copilot." },
    ],
    cta: {
      heading: "What Would Your Finance Team Ask If They Could Query Your ERP in Plain English?",
      body: "That's the question we start with. Tell us which systems hold your data and what your teams are constantly asking for — we'll show you what a copilot grounded in those systems looks like in a free session.",
      cta1: "Book a Copilot Demo",
      cta2: "See Deployment Options",
    },
    relatedServices: ["custom-ai-agent-development", "agentic-ai-finance", "data-intelligence-decision-analytics"],
  },
  {
    id: "business-process-automation",
    number: "06",
    title: "Business Process Automation Beyond Finance",
    shortTitle: "BPA Beyond Finance",
    tagline: "Beyond Finance · Operations Automation",
    slug: "/services/business-process-automation",
    seo: {
      title: "Agentic Business Process Automation — HR, Procurement & Supply Chain | AgenticSense",
      description: "AgenticSense extends agentic AI into procurement, HR, supply chain and IT operations — end-to-end workflow automation integrated with your systems of record.",
    },
    hero: {
      headline: "The Same Discipline That Transformed Finance — Applied Across Your Entire Back Office.",
      highlight: "Applied Across Your Entire Back Office.",
      sub: "Finance is where we go deepest. But the same agentic operating model — end to end, integrated with systems of record, with full audit trails — travels. We extend it into procurement, HR, supply chain and IT operations.",
      cta1: "Map Your Automation Opportunities",
      cta2: "See the Finance Approach First",
      trustLabel: "Covering operations across",
      badges: ["Procurement", "HR & Onboarding", "Supply Chain", "IT Operations"],
    },
    overview: {
      heading: "Routine Back-Office Work Drains Your Team. Agents End That.",
      lead: "The same repetitive, rules-based work that costs finance teams weeks exists across your operations — approval chains that span systems, document handling that could be automated, routing decisions that follow predictable logic.",
      body: "We build agents that own these end to end, always integrated with your systems of record. Every BPA engagement follows the same standard as our finance work: full automation, no manual steps in the middle of a workflow, clean integration with the ERP and complete audit trails.",
      stats: [
        { val: "4+", label: "Back-office domains covered" },
        { val: "Zero", label: "Manual steps mid-workflow — hard standard" },
        { val: "ERP", label: "Integrated with your systems of record" },
        { val: "Full", label: "Audit trail on every automated action" },
      ],
      cards: [
        { title: "Procurement", body: "Requisition processing, approval routing and supplier workflow automation — connected to your ERP purchasing module." },
        { title: "HR & Onboarding", body: "Onboarding document handling, policy-driven approval workflows and employee record updates — without manual form chasing." },
        { title: "Supply Chain", body: "Order processing, inventory monitoring, fulfilment tracking and supplier communication — end to end, ERP-native." },
        { title: "IT & Operations", body: "Ticket triage, routing, routine task execution and cross-system notification workflows — agents that own the process, not just pass it on." },
      ],
    },
    benefits: [
      { icon: "⏳", title: "Turnaround time cut dramatically", body: "Approval workflows that took days move in hours. Processes that required email chains and manual chasing complete end to end — automatically." },
      { icon: "📋", title: "Consistent process execution", body: "Rules are applied the same way every time — no exceptions driven by workload or individual interpretation. Compliance is a function of the system, not the person." },
      { icon: "🔗", title: "Systems of record stay current", body: "Agents update your ERP, HRMS and ITSM as they work — so downstream reports and dashboards reflect reality, not yesterday's manual update." },
      { icon: "🎯", title: "Your people focus on decisions, not administration", body: "Routing, chasing, logging and status updates are handled by the agent. Your team's attention goes to the judgements that require it." },
      { icon: "📊", title: "Cross-process visibility", body: "When agents handle the work, the data is clean. You get genuine process analytics — cycle times, bottlenecks, exception rates — because the workflow is instrumented." },
      { icon: "🔄", title: "Extends your finance automation investment", body: "Procurement agents connect directly to your AP workflow. HR automation feeds into your GL. The disciplines reinforce each other across functions." },
    ],
    features: [
      { num: "PR", title: "Procurement — Requisition to PO", body: "Automated requisition intake, budget validation, approval routing and PO creation — integrated with your ERP purchasing module." },
      { num: "PR", title: "Procurement — Supplier Workflows", body: "Supplier onboarding document handling, communication and status updates — with clean records in your vendor master." },
      { num: "HR", title: "HR — Employee Onboarding", body: "Document collection, policy acknowledgement routing and system access provisioning — completed before the employee's first day." },
      { num: "HR", title: "HR — Policy-Driven Approvals", body: "Leave requests, expense pre-approvals and role change workflows — routed according to your policy rules, not someone's memory of them." },
      { num: "SC", title: "Supply Chain — Order Processing", body: "Order confirmation, inventory allocation and fulfilment triggering — with status visible across your ERP and customer-facing systems." },
      { num: "SC", title: "Supply Chain — Inventory Monitoring", body: "Automated replenishment triggers, supplier alerts and exception-based inventory management — before stockouts become a crisis." },
      { num: "IT", title: "IT — Ticket Triage and Routing", body: "Incoming tickets classified, prioritised and routed to the right queue — with context extracted and attached, not lost in the email thread." },
      { num: "IT", title: "Cross-System Approval Workflows", body: "Approvals that span SAP, Salesforce and your ITSM platform — with a single audit trail covering every system the workflow touches." },
    ],
    process: [
      { num: "01", title: "Process Mapping", body: "We document the workflow end to end, identify where manual steps exist and prioritise by volume, cost and automation feasibility." },
      { num: "02", title: "Integration Design", body: "Every system the workflow touches is mapped — ERP, HRMS, ITSM, email — and the integration architecture is designed before build." },
      { num: "03", title: "Agent Build", body: "Development against your real process rules, approval hierarchies and system constraints — no demo-only builds." },
      { num: "04", title: "Parallel Run & Go-Live", body: "Agents run alongside existing processes during validation, then go live with monitoring and human oversight active." },
      { num: "05", title: "Expand & Optimise", body: "Additional process coverage, performance tuning and cross-function integration as the programme matures." },
    ],
    whyUs: {
      heading: "One Operating Standard — Whatever the Function",
      points: [
        { title: "Finance-grade discipline applied everywhere", body: "The same audit trail, exception handling and end-to-end automation standards we apply to AP are applied to procurement, HR, supply chain and IT." },
        { title: "Cross-function integration from the start", body: "Procurement agents connect to AP. HR feeds the GL. We design the integration landscape holistically — not one function at a time." },
        { title: "No manual steps — in any domain", body: "Full end-to-end automation is our standard across every BPA engagement. The agent finishes the task — it does not hand back halfway." },
        { title: "Genuine process audit before we build", body: "We do not build without a clear, validated process spec. Automation without process clarity fails — we identify gaps before they become defects." },
      ],
      box: {
        heading: "The Same Standard Across Every Function",
        body: "Finance-grade automation applied to procurement, HR, supply chain and IT — not a watered-down version for non-finance teams.",
        stats: [
          { val: "4+", label: "Back-office domains covered" },
          { val: "Zero", label: "Manual steps mid-workflow always" },
          { val: "Full", label: "Audit trail on every action" },
        ],
      },
    },
    faqs: [
      { q: "Do we need to automate finance first before extending to other functions?", a: "No. We can start in any domain — procurement, HR, supply chain or IT — independently of your finance automation roadmap. However, if you have existing finance agents, we will integrate with them from the start to maximise cross-function value." },
      { q: "Can agents handle approval workflows that span multiple departments?", a: "Yes. Multi-step, multi-department approval workflows are a standard delivery pattern. The agent routes based on your rules, handles escalations and keeps all parties notified — with a single audit trail across every touchpoint." },
      { q: "What happens when a process exception doesn't fit the agent's rules?", a: "The agent routes it to the appropriate human with full context — what it has done so far, what it couldn't resolve and what decision is needed. No exception is discarded, ignored or silently stalled." },
      { q: "How do you handle processes that are only partially documented?", a: "We start with a process-mapping engagement to document and validate the workflow before we build. Automation without a clear process spec fails — we do not skip this step, and we will flag gaps before they become defects." },
    ],
    cta: {
      heading: "Which Back-Office Process Drains the Most Time From Your Organisation?",
      body: "Start there. In a free session, we'll map the highest-value automation opportunity in your operations landscape, show you what an end-to-end agent looks like against your real workflow, and give you an honest estimate of effort and impact.",
      cta1: "Book a Free Process Assessment",
      cta2: "See the Finance Automation Standard",
    },
    relatedServices: ["agentic-ai-finance", "intelligent-document-processing", "erp-crm-ai-integration"],
  },
  {
    id: "data-intelligence-decision-analytics",
    number: "07",
    title: "Data Intelligence & Decision Analytics",
    shortTitle: "Data Intelligence",
    tagline: "Data Intelligence · Predictive Analytics",
    slug: "/services/data-intelligence-decision-analytics",
    seo: {
      title: "Enterprise Data Intelligence & Decision Analytics — Microsoft Fabric & AI | AgenticSense",
      description: "AgenticSense turns enterprise data into decisions — predictive analytics, anomaly detection and decision-support agents on Microsoft Fabric, Oracle and your existing data stack.",
    },
    hero: {
      headline: "Move from Reporting What Happened to Recommending What to Do Next.",
      highlight: "Recommending What to Do Next.",
      sub: "Your enterprise data holds patterns, anomalies and opportunities that static reports will never surface. We build the pipelines, models and decision-support agents that turn your historical data into forward-looking intelligence.",
      cta1: "Talk About Your Data Strategy",
      cta2: "See Analytics in Action",
      trustLabel: "Built on",
      badges: ["Microsoft Fabric", "Oracle Analytics", "Azure AI Foundry", "Your Data Stack"],
    },
    overview: {
      heading: "Intelligence That Acts — Not Just Reports That Inform",
      lead: "Dashboards tell you what happened. Predictive models tell you what will happen. Decision-support agents tell you what to do about it. We build all three — starting from your existing data sources.",
      body: "Our data intelligence practice covers the full stack: clean pipelines on Microsoft Fabric and your data infrastructure, predictive models trained on your historical data, anomaly detection across financial and operational flows, and agent-driven recommendations that surface the right action to the right person.",
      stats: [
        { val: "Live", label: "Real-time anomaly detection" },
        { val: "FWD", label: "Predictive — not just descriptive" },
        { val: "Full", label: "Pipeline from raw data to decision" },
        { val: "Exec", label: "Leadership-grade dashboards" },
      ],
      cards: [
        { title: "Executive Dashboards", body: "Real-time performance tracking for leadership — financial, operational and strategic KPIs in one governed view." },
        { title: "Predictive Analytics", body: "Cash flow forecasting, demand prediction and risk modelling trained on your historical data — not industry averages." },
        { title: "Anomaly Detection", body: "Automated flagging of unusual patterns across financial and operational flows — before they become material issues." },
        { title: "Decision-Support Agents", body: "Agents that recommend the next action — not just surface the data — so your team spends time on judgement, not investigation." },
      ],
    },
    benefits: [
      { icon: "🔮", title: "From reactive to proactive", body: "Anomalies, shortfalls and opportunities are surfaced before they become problems — giving your team time to act rather than respond." },
      { icon: "📈", title: "Forecasts built on your data", body: "Predictive models trained on your historical patterns — not industry benchmarks — deliver forecasts that reflect your actual business dynamics." },
      { icon: "🎯", title: "Leadership sees the signal, not the noise", body: "Executive dashboards surface the metrics that matter, with drill-down to the transaction level — without requiring an analyst to prepare each view." },
      { icon: "⚡", title: "Recommendations, not just reports", body: "Decision-support agents go one step further — 'here is the anomaly, here is the likely cause, here is the recommended action' — reducing cognitive load." },
      { icon: "🔗", title: "Connects your entire data landscape", body: "Pipelines draw from your ERP, CRM, operational systems and external data sources — a unified view, not siloed reports from each system." },
      { icon: "🏗", title: "Built on enterprise-grade infrastructure", body: "Microsoft Fabric for data lakehouse architecture and pipelines, Azure AI Foundry for model services — platforms your IT team can govern." },
    ],
    features: [
      { num: "01", title: "Data engineering and pipelines", body: "Clean, governed pipelines from source systems to analytics layer — on Microsoft Fabric, Azure or your existing data infrastructure." },
      { num: "02", title: "Executive performance dashboards", body: "Real-time operational and financial dashboards designed for leadership consumption — with drill-down to transaction level." },
      { num: "03", title: "Cash flow forecasting", body: "Predictive cash flow models trained on your AR/AP data — surfacing funding requirements and surplus positions weeks in advance." },
      { num: "04", title: "Demand and inventory prediction", body: "Forecasting models for inventory optimisation and demand planning — integrated with your ERP purchasing and supply chain data." },
      { num: "05", title: "Financial anomaly detection", body: "Automated flagging of unusual journal entries, duplicate payments, variance spikes and outlier transactions — before period end." },
      { num: "06", title: "Operational exception detection", body: "Monitoring across fulfilment, procurement and service delivery data — flagging performance deviations in real time." },
      { num: "07", title: "Decision-support agent layer", body: "Agents that analyse, synthesise and recommend — turning detected anomalies or forecast deviations into actionable guidance." },
      { num: "08", title: "Microsoft Fabric architecture", body: "Data lakehouse design, OneLake configuration, Dataflow pipelines and Fabric workspace governance — delivered and documented." },
    ],
    process: [
      { num: "01", title: "Data Landscape", body: "We audit your data sources, quality, granularity and governance posture — identifying what is usable now and what needs to be fixed." },
      { num: "02", title: "Pipeline Build", body: "Clean, governed pipelines from your ERP, CRM and operational systems into a unified data layer — on Fabric or your existing infrastructure." },
      { num: "03", title: "Model Development", body: "Predictive and anomaly-detection models trained on your historical data — with clear documentation of assumptions and limitations." },
      { num: "04", title: "Dashboard & Agent Layer", body: "Dashboards for your teams and decision-support agents that surface recommendations — not just data." },
      { num: "05", title: "Monitor & Retrain", body: "Ongoing model performance tracking, drift detection and retraining — so accuracy improves as your data grows." },
    ],
    whyUs: {
      heading: "From Data to Decisions — Not Just Data to Dashboards",
      points: [
        { title: "Decision-support agents, not just BI tools", body: "We go beyond dashboards. Our decision-support agents surface the anomaly, explain the likely cause and recommend the action — reducing time from insight to response." },
        { title: "Models trained on your data", body: "Predictive models are trained on your historical patterns, not industry benchmarks. Forecasts reflect your business dynamics — not someone else's average." },
        { title: "Honest about data quality", body: "We tell you what your data can and cannot support at the start. No false promises about accuracy from poor-quality inputs." },
        { title: "Enterprise infrastructure, not experimental tools", body: "Microsoft Fabric, Azure AI Foundry and your existing data stack — production-grade platforms that your IT and governance teams can manage." },
      ],
      box: {
        heading: "Proactive Intelligence",
        body: "Problems surfaced before they become material. Opportunities identified before they close. Recommendations at the point of decision.",
        stats: [
          { val: "Live", label: "Real-time anomaly detection active" },
          { val: "FWD", label: "Predictive modelling on your data" },
          { val: "Exec", label: "Leadership-grade dashboards included" },
        ],
      },
    },
    faqs: [
      { q: "Our data quality is poor. Do we need to fix that before starting?", a: "Not entirely — but we will be honest about what your data can and cannot support at the start. We identify data quality issues as part of the landscape audit and can address them as part of the engagement." },
      { q: "Do we need Microsoft Fabric or Azure, or can you work with our existing data platform?", a: "We work with your existing infrastructure. Microsoft Fabric and Azure AI Foundry are our preferred platforms for new data architectures, but we have experience across Snowflake, Databricks, Redshift and on-premise data warehouses." },
      { q: "How do decision-support agents differ from a standard dashboard?", a: "A dashboard shows you a number. A decision-support agent shows you the number, explains the likely cause, compares it to your historical pattern and suggests a specific action — reducing the time from 'I see the problem' to 'I know what to do about it'." },
      { q: "How quickly can we see early results?", a: "An initial executive dashboard over your existing ERP data can typically be live within weeks. Predictive models require more historical data and take longer to validate — we will set clear expectations on timeline by use case in the discovery phase." },
    ],
    cta: {
      heading: "What Decision Would Change If You Had 30-Day Visibility Instead of Last Month's Report?",
      body: "Start with that question. We will show you what is achievable against your current data landscape — and what the path from static reporting to forward-looking intelligence looks like in your environment.",
      cta1: "Book a Data Intelligence Session",
      cta2: "See the Analytics Stack",
    },
    relatedServices: ["conversational-ai-enterprise-copilots", "agentic-ai-finance", "agentic-ai-strategy-consulting"],
  },
  {
    id: "agentic-ai-strategy-consulting",
    number: "08",
    title: "Agentic AI Strategy & Readiness Consulting",
    shortTitle: "AI Strategy",
    tagline: "AI Strategy · Readiness Assessment",
    slug: "/services/agentic-ai-strategy-consulting",
    seo: {
      title: "Agentic AI Strategy & Readiness Assessment for Enterprise | AgenticSense",
      description: "AgenticSense delivers AI readiness assessments and sequenced automation roadmaps for enterprise — grounded in what your data, systems and controls can actually support today.",
    },
    hero: {
      headline: "A Roadmap Built on What Is Actually Buildable in Your Environment.",
      highlight: "Actually Buildable in Your Environment.",
      sub: "Before a line of code, we help you decide where agentic AI creates the most value. We assess readiness, score opportunities by impact and feasibility, and deliver a sequenced roadmap with measurable outcomes — grounded in your data and systems, not theoretical best practice.",
      cta1: "Book an AI Readiness Session",
      cta2: "See How We Assess Readiness",
      trustLabel: "Delivered across",
      badges: ["GCC", "South Asia", "Europe"],
    },
    overview: {
      heading: "Most AI Strategies Look Great on a Slide. Ours Work in Your Environment.",
      lead: "The gap between an AI strategy and working AI is almost always a readiness problem — not a technology problem. The data is incomplete. The ERP doesn't expose the right APIs. The controls aren't in place.",
      body: "Our strategy and readiness practice delivers an honest, actionable assessment of where agentic AI creates real value in your organisation — and a sequenced delivery roadmap that separates what is deployable today from what needs to be built first.",
      stats: [
        { val: "Written", label: "Success metrics agreed before build" },
        { val: "ROI", label: "Use cases scored by impact and feasibility" },
        { val: "Now vs.", label: "Deployable today vs. future state" },
        { val: "One", label: "Team from strategy through to production" },
      ],
      cards: [
        { title: "AI Readiness Assessment", body: "Systematic review of your data quality, ERP API access, controls infrastructure and process maturity — honest about gaps." },
        { title: "Use-Case Prioritisation", body: "Opportunities scored by ROI, automation feasibility, data readiness and risk — so you invest where impact is highest." },
        { title: "Target Architecture", body: "Platform selection, integration model and governance framework — the architecture that supports a five-year AI programme." },
        { title: "Sequenced Delivery Roadmap", body: "A phased execution plan with milestones, success metrics and clear ownership — ready to move into delivery without a separate planning phase." },
      ],
    },
    benefits: [
      { icon: "🗺", title: "Investment goes where it creates value", body: "Use cases prioritised by ROI and feasibility — not vendor recommendations or executive enthusiasm. The highest-value opportunities get resourced first." },
      { icon: "🚫", title: "Failed pilots stopped before they start", body: "We identify the blockers — data quality, API gaps, control weaknesses — before they surface as expensive problems mid-build." },
      { icon: "📐", title: "Architecture that supports the full programme", body: "Platform and integration decisions made once, correctly — not retrofitted at each new use case as the programme expands." },
      { icon: "✅", title: "Success metrics agreed before spend commits", body: "Every use case in the roadmap has clear, measurable outcomes agreed in writing — so ROI validation is built in, not argued about after delivery." },
      { icon: "🔗", title: "One team from strategy to production", body: "The same team that assesses your readiness builds your agents. No translation loss between strategy and engineering. No handoff risk." },
      { icon: "🏦", title: "Board-ready output", body: "The readiness assessment and roadmap are structured to support executive decision-making and board-level investment approval." },
    ],
    features: [
      { num: "D", title: "Data readiness", body: "Quality, completeness, accessibility and governance of your data. We assess whether your data can support the models and pipelines the use cases require." },
      { num: "S", title: "Systems readiness", body: "ERP API coverage, integration architecture, authentication infrastructure and the technical feasibility of connecting AI to your systems of record." },
      { num: "C", title: "Controls readiness", body: "Audit trail requirements, segregation of duties, approval structures and compliance constraints — the governance foundations your agents must respect." },
      { num: "P", title: "Process readiness", body: "Documentation quality, exception rate, volume and standardisation of target processes — determining what can be automated immediately." },
      { num: "01", title: "Use-case discovery", body: "Structured workshops to identify and capture automation opportunities across finance and operations — from your team's lived experience." },
      { num: "02", title: "ROI and feasibility scoring", body: "Each use case scored on volume, manual effort cost, automation complexity, data readiness and risk — producing a prioritised shortlist." },
      { num: "03", title: "Platform and architecture recommendation", body: "Target ERP integration model, AI infrastructure, data layer and governance framework — aligned to your existing landscape." },
      { num: "04", title: "Delivery roadmap and success metrics", body: "Phased execution plan with milestones, resource requirements, dependencies and measurable success criteria — ready to present to the board." },
    ],
    process: [
      { num: "01", title: "Landscape Review", body: "We review your ERP, data infrastructure, existing automation and control environment — without requiring extensive internal preparation." },
      { num: "02", title: "Discovery Workshops", body: "Structured sessions with finance, operations and IT leaders to surface automation opportunities from lived experience." },
      { num: "03", title: "Readiness Scoring", body: "Each opportunity assessed across data, systems, controls and process dimensions — producing an honest, evidence-based readiness score." },
      { num: "04", title: "Roadmap Design", body: "Prioritised use cases sequenced into a delivery programme with milestones, success metrics and investment stages." },
      { num: "05", title: "Handover to Delivery", body: "The same team moves into the build phase — strategy and delivery are continuous, not handed off between teams." },
    ],
    whyUs: {
      heading: "Strategy Built by the Team That Will Execute It",
      points: [
        { title: "Grounded in what is actually buildable", body: "We assess what your ERP APIs, data quality and controls infrastructure can support — including the parts where the answer is 'not yet'." },
        { title: "One team from assessment to production", body: "The people who assess your environment are the people who build in it. No translation loss. No handoff. No strategy that ignores implementation reality." },
        { title: "Honest about the blockers", body: "If your data quality is poor or your API access is limited, we tell you — before you commit budget to a build that will fail for the same reasons." },
        { title: "Board-ready deliverables", body: "The readiness assessment and roadmap are structured for executive consumption — investment stages, success metrics and risk disclosure included." },
      ],
      box: {
        heading: "Honest Before the Build Starts",
        body: "We will tell you what is deployable today and what needs to be addressed first — including the difficult parts.",
        stats: [
          { val: "4D", label: "Data, Systems, Controls, Process assessed" },
          { val: "ROI", label: "Every use case scored by impact" },
          { val: "Board", label: "Ready output for investment approval" },
        ],
      },
    },
    faqs: [
      { q: "We already have an AI strategy from a consultancy. Why do we need yours?", a: "Most AI strategies are produced by firms that do not build the systems. They are optimised for the strategy presentation, not for what happens when someone tries to build it. Our assessment is grounded in what your actual ERP APIs, data quality and controls infrastructure can support." },
      { q: "How long does a readiness assessment take?", a: "A focused assessment covering your core finance and operations landscape typically takes two to four weeks, depending on your organisation's complexity and availability. We are explicit about scope and timeline before starting." },
      { q: "What if the assessment shows we are not ready for AI yet?", a: "That is a valid and valuable outcome. We will tell you what needs to be addressed first — data gaps, API access, process documentation — and give you a clear path to readiness. An honest assessment that saves you an expensive failed pilot is worth far more than a roadmap that ignores the blockers." },
      { q: "Is the assessment separate from the build, or does the same team continue?", a: "The same team continues. This is a deliberate design choice — no translation loss between the people who assessed your environment and the people building in it. Strategy and delivery are a continuous engagement, not two separate contracts." },
    ],
    cta: {
      heading: "Before You Commit Budget to an AI Build, Know Exactly What You Are Committing to.",
      body: "A free readiness session gives you an honest view of where agentic AI creates value in your environment, what the blockers are and what a realistic first step looks like — at no cost and no obligation to proceed.",
      cta1: "Book a Free Readiness Session",
      cta2: "Download Our Readiness Framework",
    },
    relatedServices: ["agentic-ai-finance", "ai-governance-security-mlops", "custom-ai-agent-development"],
  },
  {
    id: "ai-governance-security-mlops",
    number: "09",
    title: "AI Governance, Security & MLOps",
    shortTitle: "Governance & MLOps",
    tagline: "AI Governance · Security · MLOps",
    slug: "/services/ai-governance-security-mlops",
    seo: {
      title: "Enterprise AI Governance, Security & MLOps — Auditable AI Systems | AgenticSense",
      description: "AgenticSense builds AI governance, security controls and MLOps into every enterprise agent from day one — audit-ready, monitored, and controlled from production launch through ongoing operations.",
    },
    hero: {
      headline: "Agents You Can Put in Front of an Auditor.",
      highlight: "in Front of an Auditor.",
      sub: "Enterprise AI has to be trustworthy — not just capable. We build governance, security and operational reliability into every agent from day one, so your automation stays accurate, compliant and under control long after go-live.",
      cta1: "Discuss AI Governance Requirements",
      cta2: "See Our Governance Framework",
      trustLabel: "Standards we build to",
      badges: ["Full Audit Trail", "HITL Controls", "Access-Controlled", "Continuously Monitored"],
    },
    overview: {
      heading: "Governance Is Not a Feature. It Is the Foundation.",
      lead: "Most AI projects add governance at the end — when the audit comes, or when something goes wrong. We build it from phase one. Every agent we ship has audit logging, access controls, human-in-the-loop checkpoints and monitoring active from the first day in production.",
      body: "For enterprises operating in regulated environments — finance, healthcare, government, energy — this is not optional. Our governance practice covers the full lifecycle: design, deployment, ongoing operations, retraining and performance management.",
      stats: [
        { val: "100%", label: "Agent actions logged and traceable" },
        { val: "Day 1", label: "Governance active from first production day" },
        { val: "HITL", label: "Human-in-loop on every critical path" },
        { val: "Live", label: "Continuous monitoring and alerting" },
      ],
      cards: [
        { title: "Human-in-the-Loop Controls", body: "Configurable approval gates and review checkpoints — so critical agent actions require human confirmation before execution." },
        { title: "Full Audit Logging", body: "Every agent action, tool call, model decision and exception flag logged with timestamps, inputs and outputs — complete traceability." },
        { title: "Monitoring & Alerting", body: "Real-time monitoring of agent accuracy, exception rates and performance drift — with alerting before problems reach a material level." },
        { title: "Managed Operations", body: "Ongoing support, model retraining, performance tuning and optimisation — your agents stay accurate and cost-efficient after launch." },
      ],
    },
    benefits: [
      { icon: "📋", title: "Audit-ready from day one", body: "Every agent action is logged with inputs, outputs and decision context. When the auditor asks, the trail is already there — not assembled retrospectively under pressure." },
      { icon: "🔐", title: "Access control that actually works", body: "AES-256 encrypted credentials, role-based access, Entra ID and OCI IAM integration — your security architecture is respected at every agent operation." },
      { icon: "🎛", title: "Human authority over critical decisions", body: "High-stakes actions — posting transactions, approving exceptions, modifying records — require human confirmation. The agent cannot bypass the gate." },
      { icon: "📡", title: "Performance problems caught early", body: "Monitoring tracks accuracy, exception rates and throughput in real time — so drift is caught and corrected before it affects your operations." },
      { icon: "🔄", title: "Agents improve over time", body: "Managed retraining and optimisation post-launch — your agents get more accurate as your data grows and your processes evolve." },
      { icon: "⚖️", title: "Compliance is demonstrable, not claimed", body: "Governance documentation, audit logs and control evidence are structured to support regulatory requirements — not assembled in a hurry before an inspection." },
    ],
    features: [
      { num: "01", title: "Configurable approval gates", body: "Human review required before any action above a defined threshold — amount, risk category or exception type. Configurable per workflow, per entity." },
      { num: "02", title: "Guardrails and output constraints", body: "Agent output bounded by explicit rules — preventing actions outside defined parameters, regardless of model output." },
      { num: "03", title: "Full action audit trail", body: "Every agent decision logged: tool called, input provided, output produced, decision made, action taken — with timestamps and operator identity." },
      { num: "04", title: "Secure credential management", body: "AES-256 encryption for all API keys and credentials. No hard-coded secrets. Rotation supported without rebuild." },
      { num: "05", title: "Role-based access and multi-tenancy", body: "Agent access scoped to the minimum required permissions. Multi-tenant isolation enforced at data and credential layers." },
      { num: "06", title: "Real-time performance monitoring", body: "Accuracy tracking, exception rate monitoring, throughput dashboards and latency alerting — live from day one of production." },
      { num: "07", title: "Model drift detection", body: "Statistical monitoring of model output distribution — alerting when accuracy begins to drift before it affects operational quality." },
      { num: "08", title: "Managed retraining and optimisation", body: "Scheduled and trigger-based retraining pipelines. Performance reports and optimisation recommendations delivered as part of managed support." },
    ],
    process: [
      { num: "01", title: "Design Governance", body: "Approval gate architecture, audit trail design and access control model — agreed before build begins, not added at the end." },
      { num: "02", title: "Build Controls In", body: "Guardrails, HITL checkpoints, credential management and logging built into the agent — not layered on top as an afterthought." },
      { num: "03", title: "Validate Governance", body: "Pre-launch testing of every control: approval gates, logging completeness, access scope and exception handling — documented." },
      { num: "04", title: "Launch with Monitoring", body: "Real-time dashboards, alerting and exception review workflows active from the first day in production." },
      { num: "05", title: "Operate & Improve", body: "Ongoing monitoring, drift detection, retraining and performance optimisation — the agent improves and compliance stays current." },
    ],
    whyUs: {
      heading: "Governance Built In — Not Bolted On",
      points: [
        { title: "Governance from phase one — always", body: "We do not add governance after the build is done. Every design decision — approval gates, audit trail structure, access control — is made before a line of code is written." },
        { title: "Every action is logged — by design", body: "Audit trails are not a reporting feature — they are a core architectural requirement. Every agent action is logged with full decision context from day one." },
        { title: "Multi-tenant isolation by architecture", body: "Tenant data, credentials and audit trails are separated at the architecture level — not by configuration. Cross-tenant access is not possible, regardless of user action." },
        { title: "Managed operations keeps governance current", body: "Retraining, performance tuning and compliance reviews are ongoing — not a one-time delivery. Your agents stay accurate and your governance stays current." },
      ],
      box: {
        heading: "Audit-Ready on Day One",
        body: "Governance built in from phase one costs a fraction of governance retrofitted under audit pressure.",
        stats: [
          { val: "100%", label: "Actions logged with full context" },
          { val: "Day 1", label: "Controls active from first production day" },
          { val: "AES", label: "256-bit credential encryption always" },
        ],
      },
    },
    faqs: [
      { q: "How do we demonstrate to regulators that AI actions are controlled and accountable?", a: "Every agent action in our builds is logged with the full decision context — input, model response, tool called, output produced and any human approval obtained. This log is structured for export in a format that supports regulatory review and internal audit." },
      { q: "What happens if an agent makes an error in production?", a: "The monitoring system alerts on accuracy anomalies in real time. High-risk actions require human approval before execution, so an error in agent reasoning cannot propagate to a system-of-record action without review. We also maintain rollback procedures and incident response protocols for every deployment." },
      { q: "Does the governance framework work across multi-tenant deployments?", a: "Yes. Multi-tenant isolation is a core design requirement — tenant data, credentials and audit trails are separated at the architecture level, with no cross-tenant data access possible regardless of user action." },
      { q: "Can we set different approval thresholds for different transaction types?", a: "Yes. Approval gates are configurable by transaction amount, exception type, vendor category, risk flag and workflow stage. Your control matrix is implemented in the agent architecture — the system enforces your rules, not a generic template." },
      { q: "What does ongoing managed support include?", a: "Managed support covers production monitoring and alerting, model performance reporting, scheduled retraining, compatibility checks ahead of ERP updates, and a defined response SLA for production incidents. The scope is agreed in writing before go-live." },
    ],
    cta: {
      heading: "Your Agents Will Be in Front of an Auditor Eventually. Build Them So That Is Not a Problem.",
      body: "Governance built in from day one costs a fraction of governance retrofitted under audit pressure. Tell us your compliance environment and control requirements — we will show you how we would build your agents to meet them.",
      cta1: "Discuss Governance Requirements",
      cta2: "Download Our Control Framework",
    },
    relatedServices: ["agentic-ai-finance", "custom-ai-agent-development", "agentic-ai-strategy-consulting"],
  },
];

export function getServiceById(id) {
  return services.find((s) => s.id === id);
}

export function getRelatedServices(ids) {
  return ids.map((id) => services.find((s) => s.id === id)).filter(Boolean);
}
